export default {
    products: [
      {
        _id: '1',
        name: 'Różana świeca sojowa z płatkami i pąkami róży 200 ml',
        category: 'Róża',
        image: './images/product-1.jpg',
        price: 55,
        brand: 'Świeca sojowa 100%',
        rating: 5,
        numReviews: 17,
        countInStock: 5,
      },
      {
        _id: '2',
        name: 'Różana świeca sojowa z płatkami i pąkami róży 350 ml',
        category: 'Róża',
        image: './images/product-2.jpg',
        price: 45,
        brand: 'Świeca sojowa 100%',
        rating: 4.7,
        numReviews: 19,
        countInStock: 5,
      },
      {
        _id: '3',
        name: 'Lawendowa świeca sojowa z kwiatami i gałązkami lawendy 235 ml',
        category: 'Lawenda',
        image: './images/product-3.jpg',
        price: 40,
        brand: 'Świeca sojowa 100%',
        rating: 4.6,
        numReviews: 11,
        countInStock: 5,
      },
      {
        _id: '4',
        name: 'Lawendowa świeca sojowa z kwiatami i gałązkami lawendy 500 ml',
        category: 'Lawenda',
        image: './images/product-4.jpg',
        price: 60,
        brand: 'Świeca sojowa 100%',
        rating: 5,
        numReviews: 19,
        countInStock: 5,
      },
      {
        _id: '5',
        name: 'Świeca sojowa o zapachu wiśni czyli sakura 300 ml',
        category: 'Sakura-wiśnia',
        image: './images/product-5.jpg',
        price: 50,
        brand: 'Świeca sojowa 100%',
        rating: 4.9,
        numReviews: 12,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Świeca sojowa o zpachu wiśni czyli sakura 500 ml',
        category: 'Sakura-wiśnia',
        image: './images/product-6.jpg',
        price: 60,
        brand: 'Świece sojowe 100%',
        rating: 4.9,
        numReviews: 13,
        countInStock: 6,
      },
    ],
  };